# Site
name: 'ACorporate Shop'
description: 'ACorporate Shop'
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
github: 'https://bienvenuelisis.github.io/shop-like-pinterest-jekyll/'
#baseurl: '/shop'
baseurl: 'https://shop.acorporate.fr'
avatar: 'assets/images/me.jpg'
disqus: 'acorporate'
email: 'support@acorporate.fr'

include: ["_pages"]
permalink: /:title/

# Authors
authors:
  elisis:
    name: Bienvenu Kokou AGBAVON
    avatar: "assets/images/me.jpg"
    display_name: Kokou AGBAVON
    gravatar: c9908ff7b5184aae488be00a62a75c27
    email: elisis.author@gmail.com
    web: https://bienvenuelisis.github.io/
    twitter: https://twitter.com/AgbavonB
    social: https://www.linkedin.com/in/bienvenu-agbavon/
    description: "A Java Backend Programmer. IT Ingenior. Humanist blogger. African optimist"

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

whitelist:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
      
# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 20


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]